name: Update yfinance and regenerate requirements.txt

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  update-requirements:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11  

 
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

 
    - name: Upgrade yfinance
      run: |
        pip install --upgrade yfinance

  
    - name: Freeze updated dependencies to requirements.txt
      run: |
        pip freeze > requirements.txt

 
    - name: Check for changes in requirements.txt
      run: git diff --exit-code requirements.txt || echo "requirements.txt changed"


    - name: Commit and push if updated
      run: |
        git config --global user.name "github-actions-bot"
        git config --global user.email "github-actions-bot@noreply.github.com"
        git add requirements.txt
        git commit -m "Update yfinance and regenerate requirements.txt" || echo "No changes to commit"
        git push
